default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    # Update build number to current date and time
    build_number = Time.now.strftime("%Y%m%d%H%M")
    increment_build_number(
      build_number: build_number
    )
    
    # Build the app
    gym(
      scheme: "WomenBusinessDirectory",
      export_method: "app-store",
      clean: true,
      output_directory: "build",
      include_bitcode: false
    )
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "WomenBusinessDirectory",
      device: "iPhone 15"
    )
  end

  desc "Submit a new Beta build to TestFlight"
  lane :beta do
    # Ensure we're on the main branch
    ensure_git_branch(branch: 'main')
    
    # Build the app
    build
    
    # Upload to TestFlight
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "~/.appstoreconnect/private_keys/AuthKey_#{ENV["APP_STORE_CONNECT_API_KEY_ID"]}.p8",
    )
    
    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: false,
      distribute_external: true,
      notify_external_testers: true,
      changelog: "New features and bug fixes"
    )
    
    # Clean up build artifacts
    clean_build_artifacts
  end
end 